version: '3.1'

networks:
  backend:

services:
  mysql:
    image: christianhardin/deliverable2-sql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: always

  express:
    image: christianhardin/deliverable2-node
    container_name: express_api
    networks:
      - backend
    build: .
    depends_on: 
      - mysql
    ports:
      - 4000:4000
    restart: always