version: '3.1'

networks:
  grouponedeliverable:

services:
  mysql:
    image: christianhardin/deliverable3-sql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - grouponedeliverable
    restart: always

  express:
    image: christianhardin/deliverable3-node
    container_name: express_api
    networks:
      - grouponedeliverable
    build: .
    depends_on: 
      - mysql
    ports:
      - 4000:4000
    restart: always

  angular:
    image: christianhardin/deliverable3-angular
    container_name: angular
    networks:
      - grouponedeliverable
    depends_on:
      - mysql
      - express
    ports: 
      - 4005:80
    restart: always