version: '3.1'

networks:
  backend:

services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: always
    volumes:
      - ./github_db.sql:/docker-entrypoint-initdb.d/github_db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  express:
    image: christianhardin/project-group-one
    container_name: express_api
    networks:
      - backend
    build: .
    depends_on: 
      - mysql
    ports:
      - 4000:4000
    restart: always